<a href="https://github.com/minsuk-heo/deeplearning_tutorial/blob/main/1.Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Tensor?
In deep learning, a tensor is an object represented as an n-dimensional array of numbers.          

# Why Tensor?
Most Deep Learning functions expect tensors as inputs, because Tensors can be used to represent various types of data, including images, audio, and text.

Tensors have several important properties that make them useful for deep learning.

# Property 1. Rank
Rank: The number of dimensions of a tensor is referred to as its rank. 

For example, a 2D tensor (i.e., a matrix) has a rank of 2, 
while a 3D tensor has a rank of 3.

### Numpy Codes

In [1]:
import numpy as np

In [2]:
# 0D Tensor
tensor_0d = np.array(5)
# 1D Tensor
tensor_1d = np.array([1, 2, 3, 4, 5])
# 2D Tensor
tensor_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 3D Tensor
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Property 2: Shape
Shape: The shape of a tensor describes the number of elements along each dimension. 

For example, a 2D tensor with 3 rows and 4 columns has a shape of (3, 4).

In [3]:
print(f"0D Tensor: {tensor_0d.shape}")
print(f"1D Tensor: {tensor_1d.shape}")
print(f"2D Tensor: {tensor_2d.shape}")
print(f"3D Tensor: {tensor_3d.shape}")

0D Tensor: ()
1D Tensor: (5,)
2D Tensor: (3, 3)
3D Tensor: (2, 2, 2)


# Property 3. Data Type
Tensors can be represented using various data types, such as integers or floats.

The choice of data type can have an impact on the precision and the size of the deep learning model.

In [4]:
# Create an int64 tensor
int_tensor = np.array([[1, 2], [3, 4]], dtype=np.int32)
int_nbytes = int_tensor.nbytes

# Create a float64 tensor
float_tensor = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64)
float_nbytes = float_tensor.nbytes

print(f"int64 tensor: {int_nbytes} bytes")
print(f"float64 tensor: {float_nbytes} bytes")

int64 tensor: 16 bytes
float64 tensor: 32 bytes


In [5]:
# Check the data type of the tensor
data_type = int_tensor.dtype
print("int_tensor data type:", data_type)

# Check the data type of the tensor
data_type = float_tensor.dtype
print("float_tensor data type:", data_type)

int_tensor data type: int32
float_tensor data type: float64


### Pytorch code

In [6]:
import torch

# 0-dimensional tensor (scalar)
tensor_0d = torch.tensor(7)
print("0D Tensor:")
print(tensor_0d)
print("Shape:", tensor_0d.shape)

0D Tensor:
tensor(7)
Shape: torch.Size([])


In [7]:
# 1-dimensional tensor (vector)
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor:")
print(tensor_1d)
print("Shape:", tensor_1d.shape)

1D Tensor:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])


In [8]:
# 2-dimensional tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("2D Tensor:")
print(tensor_2d)
print("Shape:", tensor_2d.shape)

2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [9]:
# 3-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [10]:
# Create a 2D tensor with integer values
tensor_int = torch.tensor([[1, 2], [3, 4]])

# Create a 2D tensor with float values
tensor_float = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Calculate byte sizes
byte_size_int = tensor_int.element_size() * tensor_int.numel()
byte_size_float = tensor_float.element_size() * tensor_float.numel()

print("Byte sizes:")
print("Integer tensor size:", byte_size_int)
print("Float tensor size:", byte_size_float)

Byte sizes:
Integer tensor size: 32
Float tensor size: 16


In [11]:
# Check the default data type
print("Default data type for integers:", tensor_int.dtype)
print("Default data type for floats:", tensor_float.dtype)

Default data type for integers: torch.int64
Default data type for floats: torch.float32


In [12]:
# Change the data type to int8 (8-bit integer)
tensor_int = tensor_int.to(torch.int8)

# Change the data type to float16 (16-bit floating-point)
tensor_float = tensor_float.to(torch.float16)

# Calculate the byte size
byte_size_int = tensor_int.element_size() * tensor_int.numel()
byte_size_float = tensor_float.element_size() * tensor_float.numel()

print("Byte size after changing to int16:", byte_size_int)
print("Byte size after changing to float16:", byte_size_float)

Byte size after changing to int16: 4
Byte size after changing to float16: 8
